# Generated by Django 3.1.5 on 2021-09-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(choices=[('blood donor', 'blood donor'), ('organ donor', 'organ donor'), ('organ recipient', 'organ recipient')], max_length=100, null=True),
        ),
    ]
