# Generated by Django 3.1.5 on 2021-09-30 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organ', '0005_auto_20210930_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='donor',
        ),
    ]
