# Generated by Django 3.1.5 on 2021-10-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organ', '0006_auto_20210930_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='story',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
