# Generated by Django 3.1.5 on 2021-10-05 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organ', '0008_auto_20211006_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organ.donor'),
        ),
    ]
